<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PkgPackagesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run(): void
    {
        \DB::table('pkg_packages')->delete();

        \DB::table('pkg_packages')->insert([
            0 => [
                'id' => 1,
                'name' => 'Apache',
                'icon' => 'apache.png',
                'description' => 'Apache web server',
                'developer' => 'apache developer',
                'developer_link' => 'https://www.apache.org',
                'category' => '["Utilities"]',
                'installed_version' => null,
                'installed_version_type' => 'stable',
                'installation_status' => 'Installed',
                'has_config' => 1,
                'config_route' => 'apache/config',
                'can_remove' => 0,
                'newest_version' => null,
                'newest_version_type' => null,
                'newest_version_url' => null,
                'newest_version_filename' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            1 => [
                'id' => 2,
                'name' => 'MariaDB',
                'icon' => 'mariadb.png',
                'description' => 'Maria DB server',
                'developer' => 'MariaDB',
                'developer_link' => 'https://mariadb.org/',
                'category' => '["Utilities"]',
                'installed_version' => null,
                'installed_version_type' => 'stable',
                'installation_status' => 'Installed',
                'has_config' => 1,
                'config_route' => 'mariadb/config',
                'can_remove' => 0,
                'newest_version' => null,
                'newest_version_type' => null,
                'newest_version_url' => null,
                'newest_version_filename' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            2 => [
                'id' => 3,
                'name' => 'PHP8',
                'icon' => 'php.png',
                'description' => 'PHP 8.0',
                'developer' => 'PHP',
                'developer_link' => 'https://www.php.net',
                'category' => '["Utilities"]',
                'installed_version' => null,
                'installed_version_type' => 'stable',
                'installation_status' => 'Installed',
                'has_config' => 1,
                'config_route' => 'php8/config',
                'can_remove' => 0,
                'newest_version' => null,
                'newest_version_type' => null,
                'newest_version_url' => null,
                'newest_version_filename' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            3 => [
                'id' => 4,
                'name' => 'Redis',
                'icon' => 'redis.png',
                'description' => 'Redis Server',
                'developer' => 'Redis',
                'developer_link' => 'https://redis.io',
                'category' => '["Utilities"]',
                'installed_version' => null,
                'installed_version_type' => 'stable',
                'installation_status' => 'Installed',
                'has_config' => 1,
                'config_route' => 'redis/config',
                'can_remove' => 0,
                'newest_version' => null,
                'newest_version_type' => null,
                'newest_version_url' => null,
                'newest_version_filename' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            4 => [
                'id' => 5,
                'name' => 'Lollypop',
                'icon' => 'lollypop.png',
                'description' => 'Music Player',
                'developer' => 'Gnome',
                'developer_link' => 'https://wiki.gnome.org/Apps/Lollypop',
                'category' => '["Media"]',
                'installed_version' => null,
                'installed_version_type' => 'stable',
                'installation_status' => null,
                'has_config' => 0,
                'config_route' => null,
                'can_remove' => 1,
                'newest_version' => null,
                'newest_version_type' => null,
                'newest_version_url' => null,
                'newest_version_filename' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            5 => [
                'id' => 6,
                'name' => 'phpMyAdmin',
                'icon' => 'phpmyadmin.svg',
                'description' => 'phpMyAdmin',
                'developer' => 'Gnome',
                'developer_link' => 'https://wiki.gnome.org/Apps/Lollypop',
                'category' => '["Media"]',
                'installed_version' => null,
                'installed_version_type' => 'stable',
                'installation_status' => 'Installed',
                'has_config' => 1,
                'config_route' => 'http://localhost:8080/phpmyadmin',
                'can_remove' => 1,
                'newest_version' => null,
                'newest_version_type' => null,
                'newest_version_url' => null,
                'newest_version_filename' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            6 => [
                'id' => 7,
                'name' => 'Plex',
                'icon' => 'plex.jpg',
                'description' => 'Plex Media Server',
                'developer' => 'Plex',
                'developer_link' => 'https://www.plex.tv',
                'category' => '["Media"]',
                'installed_version' => null,
                'installed_version_type' => null,
                'installation_status' => null,
                'has_config' => 1,
                'config_route' => 'http://localhost:32400/web/index.html',
                'can_remove' => 1,
                'newest_version' => '1.23.4.4712',
                'newest_version_type' => 'stable',
                'newest_version_url' => 'https://downloads.plex.tv/plex-media-server-new/1.23.4.4712-1f0ed4aea/debian/plexmediaserver_1.23.4.4712-1f0ed4aea_amd64.deb',
                'newest_version_filename' => 'plexmediaserver_1.23.4.4712-1f0ed4aea_amd64.deb',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            7 => [
                'id' => 8,
                'name' => 'Docker',
                'icon' => 'docker.png',
                'description' => 'Docker',
                'developer' => 'Docker',
                'developer_link' => 'https://www.docker.com/',
                'category' => '["Utilities"]',
                'installed_version' => null,
                'installed_version_type' => null,
                'installation_status' => null,
                'has_config' => 0,
                'config_route' => null,
                'can_remove' => 0,
                'newest_version' => null,
                'newest_version_type' => null,
                'newest_version_url' => 'https://download.docker.com/linux/ubuntu/dists/focal/stable/binary-amd64/Release',
                'newest_version_filename' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            8 => [
                'id' => 9,
                'name' => 'VirtualBox',
                'icon' => 'virtualbox.png',
                'description' => 'VirtualBox VM',
                'developer' => 'virtualbox',
                'developer_link' => 'https://www.virtualbox.org/',
                'category' => '["Utilities"]',
                'installed_version' => null,
                'installed_version_type' => null,
                'installation_status' => null,
                'has_config' => 0,
                'config_route' => null,
                'can_remove' => 0,
                'newest_version' => '6.1_6.1.22-144080',
                'newest_version_type' => 'stable',
                'newest_version_url' => 'https://download.virtualbox.org/virtualbox/6.1.22/virtualbox-6.1_6.1.22-144080~Ubuntu~bionic_amd64.deb',
                'newest_version_filename' => 'virtualbox-6.1_6.1.22-144080~Ubuntu~bionic_amd64.deb',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            9 => [
                'id' => 10,
                'name' => 'KonnecPhotos',
                'icon' => 'photos.png',
                'description' => 'Konnec Photos',
                'developer' => 'Konnec',
                'developer_link' => 'tbd',
                'category' => '["Media"]',
                'installed_version' => null,
                'installed_version_type' => null,
                'installation_status' => null,
                'has_config' => 1,
                'config_route' => 'http://photos.nas',
                'can_remove' => 1,
                'newest_version' => null,
                'newest_version_type' => null,
                'newest_version_url' => null,
                'newest_version_filename' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            10 => [
                'id' => 11,
                'name' => 'FileStation',
                'icon' => 'filestation.jpg',
                'description' => 'Konnec File Statio',
                'developer' => 'Konnec',
                'developer_link' => 'tbd',
                'category' => '["Utilities"]',
                'installed_version' => null,
                'installed_version_type' => null,
                'installation_status' => null,
                'has_config' => 1,
                'config_route' => 'http://file.nas',
                'can_remove' => 1,
                'newest_version' => null,
                'newest_version_type' => null,
                'newest_version_url' => null,
                'newest_version_filename' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            11 => [
                'id' => 12,
                'name' => 'Surveillance Station',
                'icon' => 'surveillance.png',
                'description' => 'Konnec Surveillance Station',
                'developer' => 'Konnec',
                'developer_link' => 'tbd',
                'category' => '["Media"]',
                'installed_version' => null,
                'installed_version_type' => null,
                'installation_status' => null,
                'has_config' => 1,
                'config_route' => 'http://camera.nas',
                'can_remove' => 1,
                'newest_version' => null,
                'newest_version_type' => null,
                'newest_version_url' => null,
                'newest_version_filename' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
        ]);
    }
}
