services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    environment:
      - JELLYFIN_PublishedServerUrl=http://26.11.80.111
    volumes:
      - /srv/docker/jellyfin/config:/config
      - /srv/docker/jellyfin/cache:/cache
      - type: bind
        source: /mnt/volume0/media
        target: /media
    restart: 'unless-stopped'
